version: '3.4'

networks:
  mynetwork:

services:
  schedule:
    image: furlupe/schedule:latest
    env_file: ./app.env
    depends_on: 
      - database
    ports:
      - "5000:80"
    networks:
      - mynetwork

  database:
    image: postgres:alpine
    env_file: ./db.env
    ports:
      - "5433:5432"
    networks:
      - mynetwork